# Generated by Django 5.1 on 2024-09-03 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_leave_leave_request_alter_leave_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='start_date',
        ),
        migrations.AddField(
            model_name='leave',
            name='approved_end_date',
            field=models.DateField(default=datetime.date(2024, 9, 3)),
        ),
        migrations.AddField(
            model_name='leave',
            name='approved_start_date',
            field=models.DateField(default=datetime.date(2024, 9, 3)),
        ),
        migrations.AddField(
            model_name='leave',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='requested_end_date',
            field=models.DateField(default=datetime.date(2024, 9, 3)),
        ),
        migrations.AddField(
            model_name='leave',
            name='requested_start_date',
            field=models.DateField(default=datetime.date(2024, 9, 3)),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
