# Generated by Django 5.1 on 2024-09-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_remove_leave_end_date_remove_leave_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='approved_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leave',
            name='approved_start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leave',
            name='requested_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leave',
            name='requested_start_date',
            field=models.DateField(),
        ),
    ]
