# Generated by Django 5.1 on 2024-09-05 05:05

import django.db.models.deletion
import employees.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('designation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designation_name', models.CharField(max_length=255)),
                ('responsibilities', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('date_of_birth', models.DateField()),
                ('date_of_joining', models.DateField()),
                ('address', models.CharField(default='No Address', max_length=255)),
                ('has_profile_edit', models.BooleanField(default=False)),
                ('emergency_contact_number', models.CharField(max_length=20)),
                ('emergency_contact_name', models.CharField(max_length=255)),
                ('emergency_contact_relationship', models.CharField(default='Emergency Contact', max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_account_number', models.CharField(max_length=255)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('bank_branch', models.CharField(max_length=255)),
                ('has_bank_account_edit', models.BooleanField(default=False)),
                ('experience_description', models.TextField()),
                ('role', models.CharField(choices=[('hr', 'HR'), ('employee', 'Employee')], default='employee', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='departments.department')),
                ('designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.designation')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='employees.employee')),
                ('user_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=100)),
                ('document_description', models.TextField()),
                ('document_path', models.FileField(upload_to=employees.models.get_unique_file_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('validated', models.BooleanField(default=False)),
                ('employee_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeUpdate',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('emergency_contact_number', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('emergency_contact_relationship', models.CharField(default='Emergency Contact', max_length=255)),
                ('profile_edit', models.BooleanField(default=False)),
                ('bank_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('bank_account_number', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('ifsc_code', models.CharField(blank=True, default=None, max_length=11, null=True)),
                ('bank_branch', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('bank_edit', models.BooleanField(default=False)),
                ('experience_description', models.TextField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_requests', to='employees.employee')),
            ],
        ),
    ]
