# Generated by Django 5.1 on 2024-08-28 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_rename_employee_document_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='validated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EmployeeUpdate',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField()),
                ('emergency_contact_number', models.CharField(max_length=20)),
                ('emergency_contact_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_account_number', models.CharField(max_length=255)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('experience_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_requests', to='employees.employee')),
            ],
        ),
    ]
