# Generated by Django 5.1 on 2024-08-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_document_validated_employeeupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeupdate',
            name='address',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='employeeupdate',
            name='bank_account_number',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='employeeupdate',
            name='bank_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='employeeupdate',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employeeupdate',
            name='emergency_contact_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='employeeupdate',
            name='emergency_contact_number',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeupdate',
            name='experience_description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='employeeupdate',
            name='ifsc_code',
            field=models.CharField(default=None, max_length=11),
        ),
        migrations.AlterField(
            model_name='employeeupdate',
            name='phone_number',
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
    ]
