# Generated by Django 5.1 on 2024-08-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employeeupdate_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('hr', 'HR'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
    ]
