# Generated by Django 5.1 on 2024-08-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('HR', 'HR'), ('Employee', 'Employee')], default='employee', max_length=20),
        ),
    ]
