# Generated by Django 5.1 on 2024-08-30 14:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
