# Generated by Django 5.1 on 2024-08-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_document_document_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bank_branch',
            field=models.CharField(default='trivandrum', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_relationship',
            field=models.CharField(default='Emergency Contact', max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='has_bank_account_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='has_profile_edit',
            field=models.BooleanField(default=False),
        ),
    ]
