# Generated by Django 5.1 on 2024-08-30 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('employees', '0009_employee_bank_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeupdate',
            name='bank_branch',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='employeeupdate',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='update_requests', to='departments.department'),
        ),
        migrations.AddField(
            model_name='employeeupdate',
            name='designation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='employees.designation'),
        ),
        migrations.AddField(
            model_name='employeeupdate',
            name='emergency_contact_relationship',
            field=models.CharField(default='Emergency Contact', max_length=255),
        ),
        migrations.AddField(
            model_name='employeeupdate',
            name='role',
            field=models.CharField(choices=[('hr', 'HR'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
        migrations.AddField(
            model_name='employeeupdate',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinate_requests', to='employees.employee'),
        ),
    ]
