# Generated by Django 5.1 on 2024-08-31 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_employeeupdate_bank_branch_employeeupdate_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(default='No Address', max_length=255),
        ),
        migrations.AlterField(
            model_name='employeeupdate',
            name='address',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
