# Generated by Django 5.1 on 2024-08-31 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_alter_employee_address_alter_employeeupdate_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeupdate',
            name='bank_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeupdate',
            name='profile_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employeeupdate',
            name='bank_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
