# Generated by Django 5.1 on 2024-08-31 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_employeeupdate_bank_edit_employeeupdate_profile_edit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeupdate',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employeeupdate',
            name='bank_account_number',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employeeupdate',
            name='bank_branch',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employeeupdate',
            name='bank_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employeeupdate',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employeeupdate',
            name='emergency_contact_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employeeupdate',
            name='emergency_contact_number',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employeeupdate',
            name='experience_description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='employeeupdate',
            name='ifsc_code',
            field=models.CharField(blank=True, default=None, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='employeeupdate',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, unique=True),
        ),
    ]
