# Generated by Django 5.1 on 2024-08-31 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('employees', '0013_alter_employeeupdate_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeupdate',
            name='department',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_requests', to='departments.department'),
        ),
    ]
