# Generated by Django 5.1 on 2024-08-31 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_alter_employeeupdate_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeupdate',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employeeupdate',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='employeeupdate',
            name='role',
        ),
        migrations.RemoveField(
            model_name='employeeupdate',
            name='supervisor',
        ),
    ]
