# Generated by Django 5.1 on 2024-08-31 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_remove_employeeupdate_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeupdate',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employeeupdate',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
