# Generated by Django 5.1 on 2024-09-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_alter_document_employee_id_alter_employee_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_path',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
