# Generated by Django 5.1 on 2024-09-01 16:18

import employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_alter_document_document_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_path',
            field=models.FileField(upload_to=employees.models.get_unique_file_path),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(max_length=100),
        ),
    ]
