# Generated by Django 5.1 on 2024-09-05 05:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('shift_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shift_name', models.CharField(max_length=255)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('check_in_time', models.DateTimeField(default=None, null=True)),
                ('check_out_time', models.DateTimeField(default=None, null=True)),
                ('attendance_type', models.CharField(choices=[('FullDay', 'Full Day'), ('HalfDay', 'Half Day')], default='FullDay', max_length=50)),
                ('work_type', models.CharField(choices=[('WorkFromHome', 'Work From Home'), ('WorkFromOffice', 'Work From Office')], default='WorkFromHome', max_length=50)),
                ('is_overtime', models.BooleanField(default=False)),
                ('overtime_hours', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee')),
                ('shift', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.shift')),
            ],
        ),
    ]
