# Generated by Django 5.1 on 2024-08-26 12:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='status',
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendance_type',
            field=models.CharField(choices=[('FullDay', 'Full Day'), ('HalfDay', 'Half Day')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='work_type',
            field=models.CharField(choices=[('WorkFromHome', 'Work From Home'), ('WorkFromOffice', 'Work From Office')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
