# Generated by Django 5.1 on 2024-08-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_attendance_status_attendance_attendance_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='employee',
            new_name='employee_id',
        ),
        migrations.AddField(
            model_name='attendance',
            name='overtime_hours',
            field=models.IntegerField(default=0),
        ),
    ]
