# Generated by Django 5.1 on 2024-09-03 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_rename_employee_attendance_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_type',
            field=models.CharField(choices=[('FullDay', 'Full Day'), ('HalfDay', 'Half Day')], default='FullDay', max_length=50),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_in_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_out_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='shift',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.shift'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='work_type',
            field=models.CharField(choices=[('WorkFromHome', 'Work From Home'), ('WorkFromOffice', 'Work From Office')], default='WorkFromHome', max_length=50),
        ),
    ]
